name: 08 DAST Scan

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

jobs:
  dast-owasp-zap:
    runs-on: ubuntu-latest
    name: OWASP ZAP Full Scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Levantar la aplicaci√≥n desde la imagen creada
      - name: Start Container
        run: |
          docker run -d -p 8080:8080 --name target-app ${{ inputs.image-tag }}
          sleep 15 # Esperar a que la app inicie

      # 2. Ejecutar el ataque con ZAP
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.9.0
        with:
          target: 'http://localhost:8080'
          # Fail si encuentra alertas de riesgo alto
          fail_action: true 
          allow_issue_writing: false # Poner en true si quieres que cree Issues en GitHub

      - name: Stop Container
        if: always()
        run: docker stop target-app