name: 01 - Secure Main Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  security-events: write
  actions: read
  packages: write
  id-token: write


jobs:
  # 1. Seguridad Primero: Si hay secretos, no seguimos.
  pre-flight-security:
    uses: ./.github/workflows/00-security-preflight.yml
    permissions:
      contents: read

  build:
    needs: pre-flight-security
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      checks: write
      pull-requests: write

  # SAST y SCA pueden correr en paralelo al build para ahorrar tiempo
  security-static-analysis:
    needs: pre-flight-security
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for parallel SAST trigger
        run: echo "Triggering SAST & SCA parallel execution"

  sast:
    needs: pre-flight-security
    uses: ./.github/workflows/sast.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  sca:
    needs: pre-flight-security
    uses: ./.github/workflows/sca.yml

  docker-build-sign:
    needs: [build, sast, sca] # Solo construimos la imagen si el código es seguro
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write
      id-token: write # CRÍTICO para Cosign

  container-scan:
    needs: docker-build-sign
    uses: ./.github/workflows/container-image-scan.yml
    with:
      image-tag: ${{ needs.docker-build-sign.outputs.image-tag }}
    permissions:
      contents: read
      security-events: write

  dast:
    needs: container-scan # Solo atacamos si la imagen pasó el scan de vulnerabilidades
    uses: ./.github/workflows/dast.yml
    with:
      image-tag: ${{ needs.docker-build-sign.outputs.image-tag }}