name: 01 - Secure Main Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
  security-events: write
  actions: read
  packages: write
  id-token: write


jobs:
  # 1. Seguridad Primero: Si hay secretos, no seguimos.
  pre-flight-security:
    uses: ./.github/workflows/00-security-preflight.yml
    permissions:
      contents: read

  build:
    needs: pre-flight-security
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      checks: write
      pull-requests: write

  # SAST y SCA pueden correr en paralelo al build para ahorrar tiempo
  security-static-analysis:
    needs: pre-flight-security
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder for parallel SAST trigger
        run: echo "Triggering SAST & SCA parallel execution"

  sast:
    needs: pre-flight-security
    uses: ./.github/workflows/sast.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  sca:
    needs: pre-flight-security
    uses: ./.github/workflows/sca.yml
